# -*- coding: utf-8 -*-
"""App(1).py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EfZ3AgdtCAk856PzLN_dMpvdB8AIOOkR
"""

import streamlit as st
import pickle
import numpy as np

# Load model
with open("best_model.pkl", "rb") as file:
    model = pickle.load(file)

st.title("🚲 Bike Demand Prediction App")

st.write("Enter the details to predict bike rental demand")

# Inputs
temperature = st.number_input("Temperature")
humidity = st.number_input("Humidity")
windspeed = st.number_input("Wind Speed")
season = st.selectbox("Season", [1, 2, 3, 4])
holiday = st.selectbox("Holiday", [0, 1])
workingday = st.selectbox("Working Day", [0, 1])
weather = st.selectbox("Weather Condition", [1, 2, 3, 4])

# Prediction
if st.button("Predict"):
    features = np.array([[temperature, humidity, windspeed, season, holiday, workingday, weather]])
    prediction = model.predict(features)

    st.success(f"Predicted Bike Demand: {int(prediction[0])}")